### ISSUE TITLE
update README with full instructions on installation and basic usage

### ISSUE THREAD

**Issue by ergz** [FlowWest/grunID#26]
update readme to include

- [ ] Overview
- [ ] Install
- [ ] Usage

**Comment by ergz** [comment]
@liz-fw you went through the process of installing and setting this up on your computer recently, can you update the README with these section. Start with a focus on the install portion where we detail all the dependencies along with links to downloads required.

**Comment by liz-fw** [comment]
@ergz I updated the overview and installation sections  in the readme branch - for the dependencies, I wrote about the structure of the data management plan but I wasn't sure if I should instead focus on what R packages were needed. Let me know!

**Comment by ergz** [comment]
@liz-fw I am back focusing on JPE again, can you open up a pull request for that branch, I can add some feedback to the PR.
